### ISSUE TITLE
"cupy.cuda.runtime.CUDARuntimeError" on running with any GPU

### ISSUE THREAD

**Issue by pcgrosen** [yusuketomoto/chainer-char-rnn#20]
Upon running `python train.py`, I receive this:

```
data/tinyshakespeare/input.txt
corpus length: 1115394
vocab size: 65
Traceback (most recent call last):
  File "train.py", line 67, in <module>
    cuda.get_device(args.gpu).use()
  File "cupy/cuda/device.pyx", line 73, in cupy.cuda.device.Device.use (cupy/cuda/device.cpp:1804)
  File "cupy/cuda/device.pyx", line 79, in cupy.cuda.device.Device.use (cupy/cuda/device.cpp:1753)
  File "cupy/cuda/runtime.pyx", line 147, in cupy.cuda.runtime.setDevice (cupy/cuda/runtime.cpp:2422)
  File "cupy/cuda/runtime.pyx", line 106, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:1815)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorUnknown: unknown error
```

This is a fresh installation of Ubuntu 15.04; I downloaded it for this purpose. Chainer was installed simply with `pip install chainer`, and I ran the Cuda installer with defaults.

Any help would be greatly appreciated.
Thanks!

**Comment by deependersingla** [comment]
@theradical  any update on this? Getting same error.

**Comment by yusuketomoto** [comment]
it seems gpu is not available on chainer.
i changed code to use cpu by default.
try again please.

**Comment by deependersingla** [comment]
For me CPU is working right from start, @yusuketomoto  so the GPU doesn't work for anyone?

**Comment by yusuketomoto** [comment]
gpu is working for me.

try `pip install chainer --no-cache` after installing CUDA and setting path.
following post might be helpful.
https://github.com/pfnet/chainer
https://goo.gl/sYx4MN

after install, you should try running `chainer/examples/mnist/train_mnist.py` on gpu to check if gpu works.

**Comment by xzyaoi** [comment]
same question here. any solutions?

**Comment by honnibal** [comment]
It's stupid, but have you tried turning it off and on again? Sometimes this happens to me and I simply have to reboot the server. I'm not sure what process needs to be restarted, but it doesn't seem to be anything to do with Chainer or cupy.
